session_name: llm_${DIRENV_NAME}
start_directory: ${PWD}
options:
  default-command: ~/llmdev/bwrap
  status-style: "bg=blue"
windows:
  - window_name: llm_${DIRENV_NAME}
    layout: even-horizontal
    suppress_history: false
    panes:
      -
      -
