#!/bin/bash

set -eu

source "$(dirname "$(realpath "$0")")/common.sh"

OPTS=(
	--die-with-parent
	--unshare-all
	--share-net
	--dev /dev
	--proc /proc
	--tmpfs /tmp
	--bind "$ENV/home" "$HOME"
	--tmpfs "$ENV"
	--tmpfs "$DIR"
)

SYSPATHS=(
	/usr
	/bin
	/lib
	/lib64
	/etc/hosts
	/etc/localtime
	/etc/ssl/certs
	/etc/resolv.conf
	/etc/nsswitch.conf
	/run/systemd/resolve
	/etc/manpath.config
	/etc/alternatives
	/etc/bash_completion.d
	/etc/bash_completion
	/etc/bash.bashrc
	/etc/locale.conf
	/etc/vim/vimrc
	/etc/inputrc
	/etc/profile
	/etc/passwd
	/etc/group
)

for syspath in "${SYSPATHS[@]}"; do
	OPTS+=(--ro-bind "$syspath" "$syspath")
done

shopt -s dotglob nullglob
for skelpath in /etc/skel/*; do
	OPTS+=(--ro-bind "$skelpath" "$HOME/$(basename "$skelpath")")
done
shopt -u dotglob nullglob

OPTS+=(--ro-bind-try "$HOME/.Xauthority" "$HOME/.Xauthority")
OPTS+=(--ro-bind-try "$HOME/.gitconfig" "$HOME/.gitconfig")
OPTS+=(--ro-bind-try "/tmp/tmux-$UID/" "/tmp/tmux-$UID/")

ENVPATHS=(
	node
	venv
	go
	dist
)

for envpath in "${ENVPATHS[@]}"; do
	OPTS+=(--ro-bind-try "$ENV/$envpath" "$ENV/$envpath")
	PATH="$ENV/$envpath/bin:$PATH"
done

OPTS+=(--bind "$ENV/tmp" "$ENV/tmp")
OPTS+=(--bind "$ENV/www" "$ENV/www")

DIRPATHS=(
	env
	src
	tmp
	lib
	wip
	llm
)

LLMPATHS=(
	.agents
	AGENTS.md
)

if test "${DIRENV_ROOT:-}"; then
	for dirpath in "${DIRPATHS[@]}"; do
		OPTS+=(--bind-try "$DIR/$dirpath" "$DIR/$dirpath")
	done

	for llmpath in "${LLMPATHS[@]}"; do
		OPTS+=(--bind-try "$DIR/$llmpath" "$DIR/$llmpath")
	done
else
	OPTS+=(--bind "$PWD" "$PWD")
fi

OPTS+=(
	--chdir "$PWD"
	--setenv "WSDIR" "$DIR"
	--setenv "WSTAG" "$TAG"
	--setenv "PATH" "$PATH"
	--setenv "VISUAL" "vim"
)


if ! test "$*"; then
	set -- "$SHELL"
fi

echo "enter"
export debian_chroot=llmdev
exec bwrap "${OPTS[@]}" -- "$@"
