#!/bin/bash

set -eu

ENV="$(readlink -f "$(dirname "$0")")"
DIR="$(realpath --relative-to="$HOME" "$PWD")"
DIR="${DIRENV_ROOT:-$DIR}"
TAG="${DIRENV_NAME:-$(basename "$DIR")}"

OPTS=(
	--die-with-parent
	--unshare-all
	--share-net
	--dev /dev
	--proc /proc
	--tmpfs /tmp
	--bind "$ENV/home" "$HOME"
	--tmpfs "$ENV"
	--tmpfs "$DIR"
)

SYSPATHS=(
	/usr
	/bin
	/lib
	/lib64
	/etc/ssl/certs
	/etc/resolv.conf
	/run/systemd/resolve
	/etc/alternatives
	/etc/bash.bashrc
	/etc/profile
	/etc/passwd
	/etc/group
)

for syspath in "${SYSPATHS[@]}"; do
	OPTS+=(--ro-bind "$syspath" "$syspath")
done

shopt -s dotglob nullglob
for skelpath in /etc/skel/*; do
	OPTS+=(--ro-bind "$skelpath" "$HOME/$(basename "$skelpath")")
done
shopt -u dotglob nullglob

ENVPATHS=(
	node
	venv
	go
	dist
)

for envpath in "${ENVPATHS[@]}"; do
	OPTS+=(--ro-bind-try "$ENV/$envpath" "$ENV/$envpath")
	PATH="$ENV/$envpath/bin:$PATH"
done

OPTS+=(--bind "$ENV/www" "$ENV/www")

DIRPATHS=(
	env
	src
	tmp
	wip
	lib
)

LLMPATHS=(
	.agents
	.claude
	.codex
	AGENTS.md
)

if test "${DIRENV_ROOT:-}"; then
	for dirpath in "${DIRPATHS[@]}"; do
		OPTS+=(--bind-try "$DIR/$dirpath" "$DIR/$dirpath")
	done

	for llmpath in "${LLMPATHS[@]}"; do
		OPTS+=(--bind-try "$DIR/llm/$llmpath" "$DIR/$llmpath")
	done
else
	OPTS+=(--bind "$PWD" "$PWD")
fi

OPTS+=(
	--chdir "$PWD"
	--setenv "WSDIR" "$DIR"
	--setenv "WSTAG" "$TAG"
	--setenv "PATH" "$PATH"
	--setenv "VISUAL" "vim"
)


if ! test "$*"; then
	set -- "$SHELL"
fi

echo "enter"
exec bwrap "${OPTS[@]}" -- "$@"
