#!/bin/sh

set -eux

ROOT="$(readlink -f "$(dirname "$0")")"
PRJ="$(realpath --relative-to="$HOME" "$PWD")"
ENV="${DIRENV_ROOT:-$PRJ}"

mkdir -p "$ROOT/tmp/$ROOT"
mkdir -p "$ROOT/tmp/$ENV"

exec bwrap \
	--unshare-all \
	--share-net \
	--dev /dev \
	--proc /proc \
	--tmpfs /tmp \
	--ro-bind /usr /usr \
	--ro-bind /bin /bin \
	--ro-bind /lib /lib \
	--ro-bind /lib64 /lib64 \
	--ro-bind /etc/ssl/certs /etc/ssl/certs \
	--ro-bind /etc/resolv.conf /etc/resolv.conf \
	--ro-bind /run/systemd/resolve /run/systemd/resolve \
	--ro-bind /etc/alternatives /etc/alternatives \
	--bind "$ROOT/home" "$HOME" \
	--bind "$ROOT/tmp/$ROOT" "$ROOT" \
	--bind "$ROOT/node/node_modules" "$ROOT/node/node_modules" \
	--bind "$ROOT/tmp/$ENV" "$ENV" \
	--bind-try "$ENV/env" "$ENV/env" \
	--bind-try "$ENV/src" "$ENV/src" \
	--bind-try "$ENV/tmp" "$ENV/tmp" \
	--bind-try "$ENV/llm/.agents" "$ENV/.agents" \
	--bind-try "$ENV/llm/.claude" "$ENV/.claude" \
	--bind-try "$ENV/llm/.codex" "$ENV/.codex" \
	--bind-try "$ENV/llm/.agents/AGENTS.md" "$ENV/AGENTS.md" \
	--bind "$PWD" "$PWD" \
	--chdir "$PWD" \
	--setenv "VISUAL" "vim" \
	"$@"
