#!/bin/sh

set -e

ROOT="$(dirname "$(readlink -f "$0")")/.."
PRJ="$(realpath --relative-to="$HOME" .)"

TTY=
if test -t 0; then
	TTY=t
fi

SRC="./src"
if ! test -d "$SRC"; then
	echo "$(readlink -f "$SRC") does not exist"
	exit 1
fi

mkdir -p ./llm/claude
exec docker run --rm -i$TTY \
	--env-file $ROOT/.env \
	--network host \
	-w /workspace/$PRJ \
	-v $ROOT/home:/home/node \
	-v ./src:/workspace/$PRJ/src \
	-v ./env:/workspace/$PRJ/env \
	-v ./llm/.claude:/workspace/$PRJ/.claude \
	local/llmdev "$@"
